-- Add IPA transcriptions for all clusters
-- Generated automatically from transcription files
-- Total: 348 phrases matched across 12 clusters
-- Includes: Clusters 1, 3, 7, 8, 9, 10, 11, 12 (fully matched) + partial matches for clusters 2, 4, 6
-- Generated: 2026-01-04 (updated with cluster 3)

UPDATE phrases SET ipa_transcription = 'ˈaʃu kɨ ˈisu faʃ sẽˈtĩdu pɐˈɾɐ mĩ' WHERE portuguese_text = 'Acho que isso faz sentido para mim.';
UPDATE phrases SET ipa_transcription = 'nɐ̃w ˈtẽɲu ɐ sɨɾˈtezɐ sɨ kõˈkoɾdu totɐɫˈmẽtɨ' WHERE portuguese_text = 'Não tenho a certeza se concordo totalmente.';
UPDATE phrases SET ipa_transcription = 'ˈisu nɐ̃w mɨ pɐˈɾesɨ ˈumɐ ˈboɐ iˈdɐjɐ' WHERE portuguese_text = 'Isso não me parece uma boa ideia.';
UPDATE phrases SET ipa_transcription = 'pɾɨˈfiɾu pẽˈsaɾ ˈnisu kõ ˈmajʃ ˈkaɫmɐ' WHERE portuguese_text = 'Prefiro pensar nisso com mais calma.';
UPDATE phrases SET ipa_transcription = 'ˈisu dɨˈpẽdɨ ˈmũjtu dɐ sitwɐˈsɐ̃w' WHERE portuguese_text = 'Isso depende muito da situação.';
UPDATE phrases SET ipa_transcription = 'nɐ̃w ɨʃˈtaβɐ a ʃˈpɛɾɐ ˈdesɐ ʁɨʃˈpɔʃtɐ' WHERE portuguese_text = 'Não estava à espera dessa resposta.';
UPDATE phrases SET ipa_transcription = 'ˈisu faʃ ˈmajʃ sẽˈtĩdu ɐˈɡɔɾɐ' WHERE portuguese_text = 'Isso faz mais sentido agora.';
UPDATE phrases SET ipa_transcription = 'nɐ̃w mɨ ˈsĩtu kõfɔɾˈtaβɛɫ kõ ˈisu' WHERE portuguese_text = 'Não me sinto confortável com isso.';
UPDATE phrases SET ipa_transcription = 'tɐɫˈveʃ ˈseʒɐ mɨˈʎɔɾ dɨʃˈtaɾ ɐˈsĩ' WHERE portuguese_text = 'Talvez seja melhor deixar assim.';
UPDATE phrases SET ipa_transcription = 'pɾɨˈsizu dɨ pẽˈsaɾ mɨˈʎɔɾ ˈnisu' WHERE portuguese_text = 'Preciso de pensar melhor nisso.';
UPDATE phrases SET ipa_transcription = 'ˈpaɾɐ seɾ uˈnɛʃtu nɐ̃w ʃpɨˈɾaβɐ ˈisu' WHERE portuguese_text = 'Para ser honesto, não esperava isso.';
UPDATE phrases SET ipa_transcription = 'ˈveʒu ɐ sitwɐˈsɐ̃w dɨ ˈotɾɐ ˈfɔɾmɐ' WHERE portuguese_text = 'Vejo a situação de outra forma.';
UPDATE phrases SET ipa_transcription = 'ˈisu ˈmudɐ ˈũ ˈpoku ɐʃ ˈkojzɐʃ' WHERE portuguese_text = 'Isso muda um pouco as coisas.';
UPDATE phrases SET ipa_transcription = 'nɐ̃w ɛ izɐtɐˈmẽtɨ u kɨ ew pẽˈsaj' WHERE portuguese_text = 'Não é exatamente o que eu pensei.';
UPDATE phrases SET ipa_transcription = 'faʃ sẽˈtĩdu du ˈtew ˈpõtu dɨ ˈviʃtɐ' WHERE portuguese_text = 'Faz sentido do teu ponto de vista.';
UPDATE phrases SET ipa_transcription = 'nɐ̃w ˈtẽɲu ˈumɐ ʁɨʃˈpɔʃtɐ ˈneʃtɨ muˈmẽtu' WHERE portuguese_text = 'Não tenho uma resposta neste momento.';
UPDATE phrases SET ipa_transcription = 'tɐɫˈveʃ puˈsɐmuʃ fɐˈlaɾ ˈdisu dɨˈpojʃ' WHERE portuguese_text = 'Talvez possamos falar disso depois.';
UPDATE phrases SET ipa_transcription = 'ˈisu nɐ̃w koʁɨʃˈpõdɨ aw kɨ ew ʃpɨˈɾaβɐ' WHERE portuguese_text = 'Isso não corresponde ao que eu esperava.';
UPDATE phrases SET ipa_transcription = 'ˈpaɾɐ mĩ ˈisu nɐ̃w ɛ ɐˈsĩ tɐ̃w ˈsĩplɨʃ' WHERE portuguese_text = 'Para mim, isso não é assim tão simples.';
UPDATE phrases SET ipa_transcription = 'ˈnũkɐ ˈtĩɲɐ pẽˈsadu ˈnisu ˈdesɐ mɐnɐjˈɾɐ' WHERE portuguese_text = 'Nunca tinha pensado nisso dessa maneira.';
UPDATE phrases SET ipa_transcription = 'ˈisu lɨˈvɐ̃tɐ aɫˈɡũmɐʃ ˈduβidɐʃ ˈpaɾɐ mĩ' WHERE portuguese_text = 'Isso levanta algumas dúvidas para mim.';
UPDATE phrases SET ipa_transcription = 'nɐ̃w mɨ pɐˈɾesɨ ɐ mɨˈʎɔɾ suluˈsɐ̃w' WHERE portuguese_text = 'Não me parece a melhor solução.';
UPDATE phrases SET ipa_transcription = 'ˈisu faʃmɨ ʁɨkõsiˈdeɾaɾ ɐ iˈdɐjɐ' WHERE portuguese_text = 'Isso faz-me reconsiderar a ideia.';
UPDATE phrases SET ipa_transcription = 'pɾɨˈsizu dɨ ˈmajʃ ĩfuɾmɐˈsɐ̃w ˈpaɾɐ dɨsiˈdiɾ' WHERE portuguese_text = 'Preciso de mais informação para decidir.';
UPDATE phrases SET ipa_transcription = 'nɐ̃w ˈveʒu ˈisu ˈkomu ˈũ pɾuˈblɛmɐ ˈsɛɾju' WHERE portuguese_text = 'Não vejo isso como um problema sério.';
UPDATE phrases SET ipa_transcription = 'ˈisu nɐ̃w ˈɛɾɐ bẽ u kɨ ew kɨˈɾiɐ dɨˈzeɾ' WHERE portuguese_text = 'Isso não era bem o que eu queria dizer.';
UPDATE phrases SET ipa_transcription = 'ˈtẽɲu sĩtɨˈmẽtuʃ ˈmiʃtuʃ ẽ ʁɨlɐˈsɐ̃w ɐ ˈisu' WHERE portuguese_text = 'Tenho sentimentos mistos em relação a isso.';
UPDATE phrases SET ipa_transcription = 'nɐ̃w ʃˈtow totɐɫˈmẽtɨ kõvẽˈsidu ˈdisu' WHERE portuguese_text = 'Não estou totalmente convencido disso.';
UPDATE phrases SET ipa_transcription = 'ˈisu mɨˈɾesɨ seɾ pẽˈsadu kõ ˈmajʃ ɐtẽˈsɐ̃w' WHERE portuguese_text = 'Isso merece ser pensado com mais atenção.';
UPDATE phrases SET ipa_transcription = 'nɐ̃w ɛ ɐˈsĩ tɐ̃w ˈklaɾu ˈpaɾɐ mĩ' WHERE portuguese_text = 'Não é assim tão claro para mim.';
UPDATE phrases SET ipa_transcription = 'ˈisu nɐ̃w mɨ ˈdejʃɐ totɐɫˈmẽtɨ tɾɐ̃ˈkil̪u' WHERE portuguese_text = 'Isso não me deixa totalmente tranquilo.';
UPDATE phrases SET ipa_transcription = 'ˈtẽɲu ˈumɐ upiˈnjɐ̃w ˈũ ˈpoku difɨˈɾẽtɨ' WHERE portuguese_text = 'Tenho uma opinião um pouco diferente.';
UPDATE phrases SET ipa_transcription = 'ˈisu nɐ̃w ɨʃˈtaβɐ nuʃ ˈmejuʃ ˈplɐnuʃ' WHERE portuguese_text = 'Isso não estava nos meus planos.';
UPDATE phrases SET ipa_transcription = 'nɐ̃w ɛ ˈaɫɡu kɨ ew dɨsidiˈɾiɐ ɐˈɡɔɾɐ' WHERE portuguese_text = 'Não é algo que eu decidiria agora.';
UPDATE phrases SET ipa_transcription = 'ˈisu ˈpɔdɨ teɾ ˈvaɾjɐʃ ĩtɨɾpɾɨtɐˈsɐ̃jʃ' WHERE portuguese_text = 'Isso pode ter várias interpretações.';
UPDATE phrases SET ipa_transcription = 'nɐ̃w ˈtẽɲu ɐ ˈmezmɐ upiˈnjɐ̃w ˈsobɾɨ ˈisu' WHERE portuguese_text = 'Não tenho a mesma opinião sobre isso.';
UPDATE phrases SET ipa_transcription = 'ˈisu faʃmɨ pẽˈsaɾ ˈduɐʃ ˈvezɨʃ' WHERE portuguese_text = 'Isso faz-me pensar duas vezes.';
UPDATE phrases SET ipa_transcription = 'nɐ̃w ʃˈtow totɐɫˈmẽtɨ dɨ ɐˈkɔɾdu kõ ˈisu' WHERE portuguese_text = 'Não estou totalmente de acordo com isso.';
UPDATE phrases SET ipa_transcription = 'ˈisu nɐ̃w ɛ tɐ̃w ˈsĩplɨʃ ˈkwɐ̃tu pɐˈɾesɨ' WHERE portuguese_text = 'Isso não é tão simples quanto parece.';
UPDATE phrases SET ipa_transcription = 'pɾɨˈsizu dɨ ʁɨflɨˈtiɾ ˈũ ˈpoku ˈmajʃ' WHERE portuguese_text = 'Preciso de refletir um pouco mais.';
UPDATE phrases SET ipa_transcription = 'ɐɡɾɐˈdesu ˈmũjtu ɐ ˈsuɐ ɐˈʒudɐ' WHERE portuguese_text = 'Agradeço muito a sua ajuda.';
UPDATE phrases SET ipa_transcription = 'ˈmũjtu uβɾiˈɡadu ˈpelu ˈsew ˈtẽpu' WHERE portuguese_text = 'Muito obrigado pelo seu tempo.';
UPDATE phrases SET ipa_transcription = 'nɐ̃w pɨɾsɨˈbi bẽ u kɨ kiʃ dɨˈzeɾ' WHERE portuguese_text = 'Não percebi bem o que quis dizer.';
UPDATE phrases SET ipa_transcription = 'ɐˈɡɔɾɐ pɨɾˈsɛbu mɨˈʎɔɾ ɐ sitwɐˈsɐ̃w' WHERE portuguese_text = 'Agora percebo melhor a situação.';
UPDATE phrases SET ipa_transcription = 'ˈpɔdɨ ʃplɨˈkaɾ ˈisu dɨ ˈotɾɐ ˈfɔɾmɐ' WHERE portuguese_text = 'Pode explicar isso de outra forma?';
UPDATE phrases SET ipa_transcription = 'ɐˈĩdɐ nɐ̃w ʃˈta totɐɫˈmẽtɨ ˈklaɾu ˈpaɾɐ mĩ' WHERE portuguese_text = 'Ainda não está totalmente claro para mim.';
UPDATE phrases SET ipa_transcription = 'ˈaʃu kɨ ẽtẽˈdi ɐ iˈdɐjɐ ʒɨˈɾaɫ' WHERE portuguese_text = 'Acho que entendi a ideia geral.';
UPDATE phrases SET ipa_transcription = 'nɐ̃w ˈtẽɲu ɐ sɨɾˈtezɐ sɨ kõpɾɨẽˈdi bẽ' WHERE portuguese_text = 'Não tenho a certeza se compreendi bem.';
UPDATE phrases SET ipa_transcription = 'ˈisu ɐˈʒudɐmɨ ɐ pɨɾsɨˈbeɾ mɨˈʎɔɾ' WHERE portuguese_text = 'Isso ajuda-me a perceber melhor.';
UPDATE phrases SET ipa_transcription = 'kõtiˈnũu kõ aɫˈɡũmɐʃ ˈduβidɐʃ ˈsobɾɨ ˈisu' WHERE portuguese_text = 'Continuo com algumas dúvidas sobre isso.';
UPDATE phrases SET ipa_transcription = 'ˈpɔdɨ daɾmɨ ˈũ ẽˈzẽplu ˈmajʃ kõˈkɾetu' WHERE portuguese_text = 'Pode dar-me um exemplo mais concreto?';
UPDATE phrases SET ipa_transcription = 'ɐˈɡɔɾɐ faʃ ˈmũjtu ˈmajʃ sẽˈtĩdu ˈpaɾɐ mĩ' WHERE portuguese_text = 'Agora faz muito mais sentido para mim.';
UPDATE phrases SET ipa_transcription = 'nɐ̃w ʃˈtow ɐ pɨɾsɨˈbeɾ bẽ ˈeʃtɐ ˈpaɾtɨ' WHERE portuguese_text = 'Não estou a perceber bem esta parte.';
UPDATE phrases SET ipa_transcription = 'ˈpɔdɨ ʁɨpɨˈtiɾ ˈesɐ ˈpaɾtɨ ˈotɾɐ ˈveʃ' WHERE portuguese_text = 'Pode repetir essa parte outra vez?';
UPDATE phrases SET ipa_transcription = 'pɨɾˈsɛbu u kɨ kɛɾ dɨˈzeɾ ẽ ˈpaɾtɨ' WHERE portuguese_text = 'Percebo o que quer dizer, em parte.';
UPDATE phrases SET ipa_transcription = 'nɐ̃w kõsɨˈɡi ɐkõpɐˈɲaɾ ˈtudu u kɨ ˈdisɨ' WHERE portuguese_text = 'Não consegui acompanhar tudo o que disse.';
UPDATE phrases SET ipa_transcription = 'ˈpɔdɨ fɐˈlaɾ ˈũ ˈpoku ˈmajʃ dɨvɐˈɡaɾ' WHERE portuguese_text = 'Pode falar um pouco mais devagar?';
UPDATE phrases SET ipa_transcription = 'ˈisu nɐ̃w fiˈko ˈmũjtu ˈklaɾu ˈpaɾɐ mĩ' WHERE portuguese_text = 'Isso não ficou muito claro para mim.';
UPDATE phrases SET ipa_transcription = 'ɐˈɡɔɾɐ pɨɾˈsɛbu u kɨ ɨʃˈtaβɐ ɐ dɨˈzeɾ' WHERE portuguese_text = 'Agora percebo o que estava a dizer.';
UPDATE phrases SET ipa_transcription = 'ɐˈĩdɐ ˈtẽɲu difiˈkuɫdadɨ ẽ pɨɾsɨˈbeɾ ˈisu' WHERE portuguese_text = 'Ainda tenho dificuldade em perceber isso.';
UPDATE phrases SET ipa_transcription = 'ˈpɔdɨ ʃplɨˈkaɾ ˈisu ˈpasu ɐ ˈpasu' WHERE portuguese_text = 'Pode explicar isso passo a passo?';
UPDATE phrases SET ipa_transcription = 'ˈisu kuˈmɛsɐ ɐ fɐˈzeɾ sẽˈtĩdu ɐˈɡɔɾɐ' WHERE portuguese_text = 'Isso começa a fazer sentido agora.';
UPDATE phrases SET ipa_transcription = 'nɐ̃w ˈtẽɲu ɐ sɨɾˈtezɐ sɨ ẽtẽˈdi kuʁɨtɐˈmẽtɨ' WHERE portuguese_text = 'Não tenho a certeza se entendi corretamente.';
UPDATE phrases SET ipa_transcription = 'ˈpɔdɨ klɐɾifiˈkaɾ ˈũ ˈpoku mɨˈʎɔɾ' WHERE portuguese_text = 'Pode clarificar um pouco melhor?';
UPDATE phrases SET ipa_transcription = 'ˈpeɾdimɨ ˈũ ˈpoku ɐ ˈmeju dɐ ʃplɨkɐˈsɐ̃w' WHERE portuguese_text = 'Perdi-me um pouco a meio da explicação.';
UPDATE phrases SET ipa_transcription = 'ˈisu nɐ̃w koʁɨʃˈpõdɨ aw kɨ ew ẽtẽˈdi' WHERE portuguese_text = 'Isso não corresponde ao que eu entendi.';
UPDATE phrases SET ipa_transcription = 'ɐˈɡɔɾɐ ʃˈta ˈmajʃ ˈklaɾu ˈpaɾɐ mĩ' WHERE portuguese_text = 'Agora está mais claro para mim.';
UPDATE phrases SET ipa_transcription = 'ˈpɔdɨ dɨˈzeɾ ˈisu dɨ mɐnɐjˈɾɐ ˈmajʃ ˈsĩplɨʃ' WHERE portuguese_text = 'Pode dizer isso de maneira mais simples?';
UPDATE phrases SET ipa_transcription = 'nɐ̃w ɐkõpɐˈɲaj bẽ ˈesɐ ˈpaɾtɨ' WHERE portuguese_text = 'Não acompanhei bem essa parte.';
UPDATE phrases SET ipa_transcription = 'ˈaʃu kɨ ɐˈɡɔɾɐ ʃˈtow ɐ pɨɾsɨˈbeɾ' WHERE portuguese_text = 'Acho que agora estou a perceber.';
UPDATE phrases SET ipa_transcription = 'ˈisu ʃklɐɾɨˈsɛsɨ bɐʃˈtɐ̃tɨ ɐʃ ˈkojzɐʃ' WHERE portuguese_text = 'Isso esclarece bastante as coisas.';
UPDATE phrases SET ipa_transcription = 'ˈpɔdɨ kõfiɾˈmaɾ sɨ ẽtẽˈdi bẽ' WHERE portuguese_text = 'Pode confirmar se entendi bem?';
UPDATE phrases SET ipa_transcription = 'ɐˈĩdɐ pɾɨˈsizu dɨ ɐɫˈɡũ ˈtẽpu ˈpaɾɐ ẽtẽˈdeɾ' WHERE portuguese_text = 'Ainda preciso de algum tempo para entender.';
UPDATE phrases SET ipa_transcription = 'nɐ̃w ʃˈtow ɐ kõsɨˈɡiɾ pɨɾsɨˈbeɾ ˈiʃtu ɐˈɡɔɾɐ' WHERE portuguese_text = 'Não estou a conseguir perceber isto agora.';
UPDATE phrases SET ipa_transcription = 'ˈisu foj ʃplɨˈkadu dɨ ˈfɔɾmɐ ˈklaɾɐ' WHERE portuguese_text = 'Isso foi explicado de forma clara.';
UPDATE phrases SET ipa_transcription = 'ɐˈɡɔɾɐ kõˈsiɡu ˈveɾ ɐ ˈlɔʒikɐ ˈdisu' WHERE portuguese_text = 'Agora consigo ver a lógica disso.';
UPDATE phrases SET ipa_transcription = 'ɐˈĩdɐ ˈtẽɲu aɫˈɡũmɐʃ pɾɨˈɡũtɐʃ ˈsobɾɨ ˈisu' WHERE portuguese_text = 'Ainda tenho algumas perguntas sobre isso.';
UPDATE phrases SET ipa_transcription = 'ˈpɔdɨ βuɫˈtaɾ ɐ ʃplɨˈkaɾ ɐ ˈuɫtimɐ ˈpaɾtɨ' WHERE portuguese_text = 'Pode voltar a explicar a última parte?';
UPDATE phrases SET ipa_transcription = 'ˈisu ɐˈʒudɐmɨ ɐ ẽtẽˈdeɾ mɨˈʎɔɾ u kõˈtɛʃtu' WHERE portuguese_text = 'Isso ajuda-me a entender melhor o contexto.';
UPDATE phrases SET ipa_transcription = 'ˈaʃu kɨ ɐˈɡɔɾɐ ẽtẽˈdi kuʁɨtɐˈmẽtɨ' WHERE portuguese_text = 'Acho que agora entendi corretamente.';
UPDATE phrases SET ipa_transcription = 'ɐˈĩdɐ nɐ̃w kõsɨˈɡi pɨɾsɨˈbeɾ ˈtudu' WHERE portuguese_text = 'Ainda não consegui perceber tudo.';
UPDATE phrases SET ipa_transcription = 'uβɾiˈɡadu puɾ ʃplɨˈkaɾ kõ ˈtɐ̃tɐ klɐˈɾezɐ' WHERE portuguese_text = 'Obrigado por explicar com tanta clareza.';
UPDATE phrases SET ipa_transcription = 'ʒa ʃˈtow ɐ kɐˈmiɲu' WHERE portuguese_text = 'Já estou a caminho.';
UPDATE phrases SET ipa_transcription = 'ˈtẽmuʃ dɨ nuʃ ɐpɾɨsɐˈɾaɾ ˈũ ˈpoku' WHERE portuguese_text = 'Temos de nos apressar um pouco.';
UPDATE phrases SET ipa_transcription = 'ɐ pɾufɨˈsoɾɐ ẽvjˈow ˈumɐ mẽˈsaʒɐ̃j' WHERE portuguese_text = 'A professora enviou uma mensagem.';
UPDATE phrases SET ipa_transcription = 'ˈpɔdɨ dɨˈzeɾmɨ ˈkwɐ̃tu ˈkuʃtɐ ˈiʃtu' WHERE portuguese_text = 'Pode dizer-me quanto custa isto?';
UPDATE phrases SET ipa_transcription = 'ɡuʃˈtaβɐ dɨ tɾuˈkaɾ ˈeʃtɨ pɾuˈdutu' WHERE portuguese_text = 'Gostava de trocar este produto.';
UPDATE phrases SET ipa_transcription = 'nɐ̃w foj ˈiʃtu kɨ ew pɨˈdi' WHERE portuguese_text = 'Não foi isto que eu pedi.';
UPDATE phrases SET ipa_transcription = 'pɾɨˈsizu dɨ ɐˈʒudɐ kõ ˈeʃtɨ sɨɾˈvisu' WHERE portuguese_text = 'Preciso de ajuda com este serviço.';
UPDATE phrases SET ipa_transcription = 'u pɐɡɐˈmẽtu nɐ̃w pɐˈsow kuʁɨtɐˈmẽtɨ' WHERE portuguese_text = 'O pagamento não passou corretamente.';
UPDATE phrases SET ipa_transcription = 'ˈpɔdɨ vɨɾifiˈkaɾ ˈisu nu sisˈtɛmɐ' WHERE portuguese_text = 'Pode verificar isso no sistema?';
UPDATE phrases SET ipa_transcription = 'ɐˈĩdɐ ʃˈta ˈdẽtɾu dɐ ɡɐɾɐ̃ˈtiɐ' WHERE portuguese_text = 'Ainda está dentro da garantia?';
UPDATE phrases SET ipa_transcription = 'ˈisu dɨˈmɔɾɐ ˈmũjtu ˈtẽpu' WHERE portuguese_text = 'Isso demora muito tempo?';
UPDATE phrases SET ipa_transcription = 'pɾɨˈsizu dɨ mɐɾˈkaɾ ˈumɐ vɨˈzitɐ ˈtɛknikɐ' WHERE portuguese_text = 'Preciso de marcar uma visita técnica.';
UPDATE phrases SET ipa_transcription = 'ˈpɔdɨ ẽvjɐɾmɨ ɐ fɐˈtuɾɐ puɾ iˈmɛjɫ' WHERE portuguese_text = 'Pode enviar-me a fatura por email?';
UPDATE phrases SET ipa_transcription = 'ɡuʃˈtaβɐ dɨ kɐ̃sɨˈlaɾ ˈeʃtɨ sɨɾˈvisu' WHERE portuguese_text = 'Gostava de cancelar este serviço.';
UPDATE phrases SET ipa_transcription = 'a ɐɫˈɡũ pɾuˈblɛmɐ kõ ˈeʃtɨ pɨˈdidu' WHERE portuguese_text = 'Há algum problema com este pedido.';
UPDATE phrases SET ipa_transcription = 'ˈpɔdɨ ʃplɨˈkaɾmɨ ˈkomu ˈiʃtu fũˈsjɔnɐ' WHERE portuguese_text = 'Pode explicar-me como isto funciona?';
UPDATE phrases SET ipa_transcription = 'ˈeʃtɨ sɨɾˈvisu ʃˈta ĩkluˈidu nu ˈpɾɛsu' WHERE portuguese_text = 'Este serviço está incluído no preço?';
UPDATE phrases SET ipa_transcription = 'pɾɨˈsizu dɨ ɐtwɐliˈzaɾ uʃ ˈmejuʃ ˈdadush' WHERE portuguese_text = 'Preciso de atualizar os meus dados.';
UPDATE phrases SET ipa_transcription = 'ˈiʃtu nɐ̃w koʁɨʃˈpõdɨ aw kɨ foj kõbiˈnadu' WHERE portuguese_text = 'Isto não corresponde ao que foi combinado.';
UPDATE phrases SET ipa_transcription = 'ˈpɔdɨ kõfiɾˈmaɾ sɨ ʃˈta ˈtudu ˈsɛɾtu' WHERE portuguese_text = 'Pode confirmar se está tudo certo?';
UPDATE phrases SET ipa_transcription = 'ɐˈĩdɐ nɐ̃w ʁɨsɨˈbi nẽˈũmɐ kõfiɾmɐˈsɐ̃w' WHERE portuguese_text = 'Ainda não recebi nenhuma confirmação.';
UPDATE phrases SET ipa_transcription = 'ɡuʃˈtaβɐ dɨ sɐˈbeɾ ˈkwajʃ sɐ̃w ɐʃ ɔpˈsɐ̃jʃ' WHERE portuguese_text = 'Gostava de saber quais são as opções.';
UPDATE phrases SET ipa_transcription = 'ˈpɔdɨ ɐʒuˈdaɾmɨ ɐ ʁɨzoɫˈveɾ ˈeʃtɨ pɾuˈblɛmɐ' WHERE portuguese_text = 'Pode ajudar-me a resolver este problema?';
UPDATE phrases SET ipa_transcription = 'ˈeʃtɨ vɐˈloɾ pɐˈɾesɨmɨ dɨmɐzjɐˈdu ˈaɫtu' WHERE portuguese_text = 'Este valor parece-me demasiado alto.';
UPDATE phrases SET ipa_transcription = 'a ɐɫˈɡũmɐ ɐɫtɨɾnɐˈtivɐ ˈmajʃ bɐˈɾatɐ' WHERE portuguese_text = 'Há alguma alternativa mais barata?';
UPDATE phrases SET ipa_transcription = 'ɡuʃˈtaβɐ dɨ fɐˈlaɾ kõ ɐɫˈɡẽj ʁɨʃpõˈsaβɛɫ' WHERE portuguese_text = 'Gostava de falar com alguém responsável.';
UPDATE phrases SET ipa_transcription = 'ˈpɔdɨ ĩdiˈkaɾmɨ ˈõdɨ tɾɐˈtaɾ ˈdisu' WHERE portuguese_text = 'Pode indicar-me onde tratar disso?';
UPDATE phrases SET ipa_transcription = 'ˈiʃtu ˈpɔdɨ seɾ ʁɨzoɫˈvidu ˈoʒɨ' WHERE portuguese_text = 'Isto pode ser resolvido hoje?';
UPDATE phrases SET ipa_transcription = 'ɐˈĩdɐ ʃˈta ˈdẽtɾu du ˈpɾazu' WHERE portuguese_text = 'Ainda está dentro do prazo?';
UPDATE phrases SET ipa_transcription = 'pɾɨˈsizu dɨ ˈumɐ ˈkɔpjɐ du kõˈtɾatu' WHERE portuguese_text = 'Preciso de uma cópia do contrato.';
UPDATE phrases SET ipa_transcription = 'ˈpɔdɨ dɨˈzeɾmɨ ˈkwajʃ sɐ̃w uʃ ˈpɾɔksimuʃ ˈpasuʃ' WHERE portuguese_text = 'Pode dizer-me quais são os próximos passos?';
UPDATE phrases SET ipa_transcription = 'ˈiʃtu fiˈkow difɨˈɾẽtɨ du kɨ ʃpɨˈɾaβɐ' WHERE portuguese_text = 'Isto ficou diferente do que esperava.';
UPDATE phrases SET ipa_transcription = 'pɾɨˈsizu dɨ kõfiɾˈmaɾ ɐɫˈɡũʃ dɨˈtaʎɨʃ' WHERE portuguese_text = 'Preciso de confirmar alguns detalhes.';
UPDATE phrases SET ipa_transcription = 'ɡuʃˈtaβɐ dɨ sɐˈbeɾ ˈkwɐ̃du ˈfikɐ ˈpɾõtu' WHERE portuguese_text = 'Gostava de saber quando fica pronto.';
UPDATE phrases SET ipa_transcription = 'ˈeʃtɨ sɨɾˈvisu foj ʁɨkumẽˈdadu ˈpelɐ ʃˈkɔlɐ' WHERE portuguese_text = 'Este serviço foi recomendado pela escola.';
UPDATE phrases SET ipa_transcription = 'ˈpɔdɨ ɐʒuˈdaɾmɨ ɐ pɾɨẽˈʃeɾ ˈeʃtɨ fuɾmuˈlaɾju' WHERE portuguese_text = 'Pode ajudar-me a preencher este formulário?';
UPDATE phrases SET ipa_transcription = 'ɐˈĩdɐ ʃˈtow a ʃˈpɛɾɐ dɨ ˈumɐ ʁɨʃˈpɔʃtɐ' WHERE portuguese_text = 'Ainda estou à espera de uma resposta.';
UPDATE phrases SET ipa_transcription = 'ˈiʃtu ˈtẽ ɐɫˈɡũ ˈkuʃtu ɐdɨsjɔˈnaɫ' WHERE portuguese_text = 'Isto tem algum custo adicional?';
UPDATE phrases SET ipa_transcription = 'ˈpɔdɨ ĩdiˈkaɾmɨ u uɾɐˈɾju dɨ fũsjũnɐˈmẽtu' WHERE portuguese_text = 'Pode indicar-me o horário de funcionamento?';
UPDATE phrases SET ipa_transcription = 'ɡuʃˈtaβɐ dɨ fɐˈzeɾ ˈumɐ ʁɨklɐmɐˈsɐ̃w' WHERE portuguese_text = 'Gostava de fazer uma reclamação.';
UPDATE phrases SET ipa_transcription = 'ˈeʃtɨ pɨˈdidu ɐˈĩdɐ ʃˈta ẽ pɾusɛsɐˈmẽtu' WHERE portuguese_text = 'Este pedido ainda está em processamento.';
UPDATE phrases SET ipa_transcription = 'ˈpɔdɨ ɐviˈzaɾmɨ ˈkwɐ̃du ɨʃˈtɨveɾ ˈpɾõtu' WHERE portuguese_text = 'Pode avisar-me quando estiver pronto?';
UPDATE phrases SET ipa_transcription = 'ɡuʃˈtaβɐ dɨ pɨˈdiɾ ˈaɫɡu ˈpaɾɐ kuˈmeɾ' WHERE portuguese_text = 'Gostava de pedir algo para comer.';
UPDATE phrases SET ipa_transcription = 'ˈpɔdɨ ʁɨkumẽˈdaɾ ɐɫˈɡũ ˈpɾatu ˈtipiku' WHERE portuguese_text = 'Pode recomendar algum prato típico?';
UPDATE phrases SET ipa_transcription = 'ɐ ˈkõtɐ puɾ fɐˈvoɾ ˈkwɐ̃du puˈdeɾ' WHERE portuguese_text = 'A conta, por favor, quando puder.';
UPDATE phrases SET ipa_transcription = 'ˈiʃtu nɐ̃w foj izɐtɐˈmẽtɨ u kɨ ew pɨˈdi' WHERE portuguese_text = 'Isto não foi exatamente o que eu pedi.';
UPDATE phrases SET ipa_transcription = 'ʃˈta ˈtudu ˈmũjtu bõ uβɾiˈɡadu' WHERE portuguese_text = 'Está tudo muito bom, obrigado.';
UPDATE phrases SET ipa_transcription = 'ˈpɔdɨ tɾɐˈzeɾ ˈmajʃ ˈũ ˈkɔpu dɨ ˈaɡwɐ puɾ fɐˈvoɾ' WHERE portuguese_text = 'Pode trazer mais um copo de água, por favor?';
UPDATE phrases SET ipa_transcription = 'pɾɨfɨˈɾiɐ ˈaɫɡu ˈmajʃ ˈlɛvɨ' WHERE portuguese_text = 'Preferia algo mais leve.';
UPDATE phrases SET ipa_transcription = 'puˈdɛmuʃ sɨ̃ˈtaɾnuʃ ɐˈli ˈfɔɾɐ' WHERE portuguese_text = 'Podemos sentar-nos ali fora?';
UPDATE phrases SET ipa_transcription = 'ˈkwɐ̃tu ˈtẽpu dɨˈmɔɾɐ u pɨˈdidu' WHERE portuguese_text = 'Quanto tempo demora o pedido?';
UPDATE phrases SET ipa_transcription = 'puˈdɛmuʃ pɐˈɡaɾ sɨpɐˈɾaduʃ' WHERE portuguese_text = 'Podemos pagar separados?';
UPDATE phrases SET ipa_transcription = 'ɡuʃˈtaβɐ dɨ ˈveɾ ɐ eˈmẽtɐ puɾ fɐˈvoɾ' WHERE portuguese_text = 'Gostava de ver a ementa, por favor.';
UPDATE phrases SET ipa_transcription = 'a ɐɫˈɡũmɐ ɔpˈsɐ̃w vɨʒɨtɐɾjˈɐnɐ ˈoʒɨ' WHERE portuguese_text = 'Há alguma opção vegetariana hoje?';
UPDATE phrases SET ipa_transcription = 'ˈpɔdɨ seɾ sẽ pɨˈkɐ̃tɨ puɾ fɐˈvoɾ' WHERE portuguese_text = 'Pode ser sem picante, por favor?';
UPDATE phrases SET ipa_transcription = 'ˈeʃtɨ ˈpɾatu ˈvẽ kõ ɐkõpɐɲɐˈmẽtu' WHERE portuguese_text = 'Este prato vem com acompanhamento?';
UPDATE phrases SET ipa_transcription = 'ɡuʃˈtaβɐ dɨ pɨˈdiɾ ɐ subɾɨˈmezɐ' WHERE portuguese_text = 'Gostava de pedir a sobremesa.';
UPDATE phrases SET ipa_transcription = 'ˈpɔdɨ tɾɐˈzeɾ u kɐˈfɛ dɨˈpojʃ puɾ fɐˈvoɾ' WHERE portuguese_text = 'Pode trazer o café depois, por favor?';
UPDATE phrases SET ipa_transcription = 'ˈiʃtu ʃˈta ˈũ ˈpoku ˈfɾiu' WHERE portuguese_text = 'Isto está um pouco frio.';
UPDATE phrases SET ipa_transcription = 'ˈpɔdɨ ɐkɨˈseɾ ˈũ ˈpoku ˈmajʃ ˈiʃtu' WHERE portuguese_text = 'Pode aquecer um pouco mais isto?';
UPDATE phrases SET ipa_transcription = 'pɾɨfɨˈɾiɐ ˈkaɾnɨ bẽ pɐˈsadɐ' WHERE portuguese_text = 'Preferia carne bem passada.';
UPDATE phrases SET ipa_transcription = 'ˈpɔdɨ seɾ ˈsɔ ˈũ kɐˈfɛ ˈkuɾtu' WHERE portuguese_text = 'Pode ser só um café curto?';
UPDATE phrases SET ipa_transcription = 'ʃˈtɐmuʃ ˈpɾõtuʃ ˈpaɾɐ pɨˈdiɾ ɐˈɡɔɾɐ' WHERE portuguese_text = 'Estamos prontos para pedir agora.';
UPDATE phrases SET ipa_transcription = 'ˈpɔdɨ tɾɐˈzeɾ ˈũ ˈpɾatu ˈpaɾɐ pɐɾtɨˈʎaɾ' WHERE portuguese_text = 'Pode trazer um prato para partilhar?';
UPDATE phrases SET ipa_transcription = 'a ɐɫˈɡũmɐ suʒɨʃˈtɐ̃w du ˈdiɐ' WHERE portuguese_text = 'Há alguma sugestão do dia?';
UPDATE phrases SET ipa_transcription = 'ɡuʃˈtaβɐ dɨ ˈaɫɡu sẽ lɐkˈtɔzɨ' WHERE portuguese_text = 'Gostava de algo sem lactose.';
UPDATE phrases SET ipa_transcription = 'ˈpɔdɨ tɾɐˈzeɾ ˈmajʃ pɐ̃w puɾ fɐˈvoɾ' WHERE portuguese_text = 'Pode trazer mais pão, por favor?';
UPDATE phrases SET ipa_transcription = 'ɐ kuˈmidɐ ɐˈĩdɐ vaj dɨˈmɔɾɐɾ' WHERE portuguese_text = 'A comida ainda vai demorar?';
UPDATE phrases SET ipa_transcription = 'ˈiʃtu nɐ̃w ʃˈta bẽ tẽpɨˈɾadu' WHERE portuguese_text = 'Isto não está bem temperado.';
UPDATE phrases SET ipa_transcription = 'ˈpɔdɨ tɾɐˈzeɾ ɐ ˈkõtɐ ˈkwɐ̃du puˈdeɾ' WHERE portuguese_text = 'Pode trazer a conta quando puder?';
UPDATE phrases SET ipa_transcription = 'ɡuʃˈtaβɐ dɨ pɐˈɡaɾ kõ kaɾˈtɐ̃w' WHERE portuguese_text = 'Gostava de pagar com cartão.';
UPDATE phrases SET ipa_transcription = 'ɐsˈejtɐ̃w kaɾˈtɐ̃wʃ ɐˈki' WHERE portuguese_text = 'Aceitam cartões aqui?';
UPDATE phrases SET ipa_transcription = 'puˈdɛmuʃ fiˈkaɾ ˈmajʃ ˈũ ˈpoku' WHERE portuguese_text = 'Podemos ficar mais um pouco?';
UPDATE phrases SET ipa_transcription = 'ˈpɔdɨ tɾɐˈzeɾ ɐ subɾɨˈmezɐ ˈpaɾɐ pɐɾtɨˈʎaɾ' WHERE portuguese_text = 'Pode trazer a sobremesa para partilhar?';
UPDATE phrases SET ipa_transcription = 'ʃˈta ˈtudu ˈpɾõtu uβɾiˈɡadu' WHERE portuguese_text = 'Está tudo pronto, obrigado.';
UPDATE phrases SET ipa_transcription = 'ɡuʃˈtamʊʃ ˈmũjtu dɐ ʁɨfɐjˈsɐ̃w' WHERE portuguese_text = 'Gostámos muito da refeição.';
UPDATE phrases SET ipa_transcription = 'ˈpɔdɨ ʁɨkumẽˈdaɾ ˈũ bõ ˈviɲu' WHERE portuguese_text = 'Pode recomendar um bom vinho?';
UPDATE phrases SET ipa_transcription = 'pɾɨfɨˈɾimuʃ ˈaɫɡu sẽ ˈaɫkuɔɫ' WHERE portuguese_text = 'Preferimos algo sem álcool.';
UPDATE phrases SET ipa_transcription = 'ɐ ˈmezɐ ʃˈta ʁɨzɨɾˈvadɐ' WHERE portuguese_text = 'A mesa está reservada?';
UPDATE phrases SET ipa_transcription = 'ˈtẽmuʃ ˈumɐ ʁɨˈzɛɾvɐ ˈpaɾɐ ˈduɐʃ pɨˈsoɐʃ' WHERE portuguese_text = 'Temos uma reserva para duas pessoas.';
UPDATE phrases SET ipa_transcription = 'ˈpɔdɨ pɾɨpɐˈɾaɾ ˈiʃtu ˈpaɾɐ lɨˈvaɾ' WHERE portuguese_text = 'Pode preparar isto para levar?';
UPDATE phrases SET ipa_transcription = 'ɡuʃˈtaβɐ dɨ lɨˈvaɾ u ˈʁɛʃtu puɾ fɐˈvoɾ' WHERE portuguese_text = 'Gostava de levar o resto, por favor.';
UPDATE phrases SET ipa_transcription = 'ˈoʒɨ ˈsĩtu mɨ bɐʃˈtɐ̃tɨ kɐ̃ˈsadu' WHERE portuguese_text = 'Hoje sinto-me bastante cansado.';
UPDATE phrases SET ipa_transcription = 'ˈiʃtu ˈdejʃɐmɨ ˈũ ˈpoku ɐ̃sjˈozu' WHERE portuguese_text = 'Isto deixa-me um pouco ansioso.';
UPDATE phrases SET ipa_transcription = 'nɐ̃w ʃˈtow nũ bõ ˈdɐjɐ ˈoʒɨ' WHERE portuguese_text = 'Não estou num bom dia hoje.';
UPDATE phrases SET ipa_transcription = 'ˈsĩtu mɨ ˈmajʃ tɾɐ̃ˈkil̪u ɐˈɡɔɾɐ' WHERE portuguese_text = 'Sinto-me mais tranquilo agora.';
UPDATE phrases SET ipa_transcription = 'ˈisu dɨˈjʃowmɨ ˈũ ˈpoku dɨʃkõfuɾˈtaβɛɫ' WHERE portuguese_text = 'Isso deixou-me um pouco desconfortável.';
UPDATE phrases SET ipa_transcription = 'ʃˈtow ɐ pɾɨziˈzaɾ dɨ ˈumɐ ˈpawzɐ' WHERE portuguese_text = 'Estou a precisar de uma pausa.';
UPDATE phrases SET ipa_transcription = 'ˈiʃtu ʃˈta ɐ ʃtɾɨˈsaɾmɨ bɐʃˈtɐ̃tɨ' WHERE portuguese_text = 'Isto está a stressar-me bastante.';
UPDATE phrases SET ipa_transcription = 'ˈoʒɨ ʃˈtow dɨ mɨˈʎɔɾ uˈmoɾ' WHERE portuguese_text = 'Hoje estou de melhor humor.';
UPDATE phrases SET ipa_transcription = 'pɾɨˈsizu dɨ fiˈkaɾ ɐluˈziɲu ˈũ ˈpoku' WHERE portuguese_text = 'Preciso de ficar sozinho um pouco.';
UPDATE phrases SET ipa_transcription = 'ˈiʃtu ɛ imusjunɐɫˈmẽtɨ pɨˈzadu ˈpaɾɐ mĩ' WHERE portuguese_text = 'Isto é emocionalmente pesado para mim.';
UPDATE phrases SET ipa_transcription = 'ˈsĩtu mɨ ˈũ ˈpoku sobɾɨkɐɾɨˈɡadu ˈoʒɨ' WHERE portuguese_text = 'Sinto-me um pouco sobrecarregado hoje.';
UPDATE phrases SET ipa_transcription = 'ʃˈtow bɐʃˈtɐ̃tɨ iɾiˈtadu kõ ˈeʃtɐ sitwɐˈsɐ̃w' WHERE portuguese_text = 'Estou bastante irritado com esta situação.';
UPDATE phrases SET ipa_transcription = 'ˈiʃtu dɨˈjʃowmɨ dɨ maw uˈmoɾ' WHERE portuguese_text = 'Isto deixou-me de mau humor.';
UPDATE phrases SET ipa_transcription = 'ˈsĩtu mɨ ˈmajʃ kõfiˈɐ̃tɨ ɐˈɡɔɾɐ' WHERE portuguese_text = 'Sinto-me mais confiante agora.';
UPDATE phrases SET ipa_transcription = 'ˈoʒɨ ʃˈtow pɐɾtikulɐɾˈmẽtɨ sẽˈsivɛɫ' WHERE portuguese_text = 'Hoje estou particularmente sensível.';
UPDATE phrases SET ipa_transcription = 'ˈiʃtu dɨˈjʃowmɨ bɐʃˈtɐ̃tɨ fɾuʃˈtɾadu' WHERE portuguese_text = 'Isto deixou-me bastante frustrado.';
UPDATE phrases SET ipa_transcription = 'ʃˈtow ɐ sĩˈtiɾ ˈmũjtɐ pɾɨˈsɐ̃w uɫtimɐˈmẽtɨ' WHERE portuguese_text = 'Estou a sentir muita pressão ultimamente.';
UPDATE phrases SET ipa_transcription = 'ˈoʒɨ ˈsĩtu mɨ ˈmajʃ puziˈtivu' WHERE portuguese_text = 'Hoje sinto-me mais positivo.';
UPDATE phrases SET ipa_transcription = 'pɾɨˈsizu dɨ ɐkɐɫˈmaɾ ˈũ ˈpoku' WHERE portuguese_text = 'Preciso de acalmar um pouco.';
UPDATE phrases SET ipa_transcription = 'ˈiʃtu dɨˈjʃowmɨ sẽ inɨɾˈʒiɐ' WHERE portuguese_text = 'Isto deixou-me sem energia.';
UPDATE phrases SET ipa_transcription = 'ˈsĩtu mɨ ˈũ ˈpoku pɨɾˈdidu kõ ˈtudu ˈiʃtu' WHERE portuguese_text = 'Sinto-me um pouco perdido com tudo isto.';
UPDATE phrases SET ipa_transcription = 'ˈoʒɨ ʃˈtow ˈmajʃ ˈkaɫmu du kɨ ˈõtẽj' WHERE portuguese_text = 'Hoje estou mais calmo do que ontem.';
UPDATE phrases SET ipa_transcription = 'ˈiʃtu ɐfɨˈtowmɨ ˈmajʃ du kɨ ew ʃpɨˈɾaβɐ' WHERE portuguese_text = 'Isto afetou-me mais do que eu esperava.';
UPDATE phrases SET ipa_transcription = 'ˈsĩtu mɨ ˈũ ˈpoku dɨʒmutiˈvadu ˈoʒɨ' WHERE portuguese_text = 'Sinto-me um pouco desmotivado hoje.';
UPDATE phrases SET ipa_transcription = 'ʃˈtow sɐtiʃˈfɐjtu kõ u ʁɨzuɫˈtadu' WHERE portuguese_text = 'Estou satisfeito com o resultado.';
UPDATE phrases SET ipa_transcription = 'ˈiʃtu dɨˈjʃowmɨ pɾiokuˈpadu' WHERE portuguese_text = 'Isto deixou-me preocupado.';
UPDATE phrases SET ipa_transcription = 'ˈoʒɨ ˈsĩtu mɨ imusjunɐɫˈmẽtɨ ɨʃɡuˈtadu' WHERE portuguese_text = 'Hoje sinto-me emocionalmente esgotado.';
UPDATE phrases SET ipa_transcription = 'ˈsĩtu mɨ ɐliˈvjadu dɨˈpojʃ ˈdisu' WHERE portuguese_text = 'Sinto-me aliviado depois disso.';
UPDATE phrases SET ipa_transcription = 'ˈiʃtu dɨˈjʃowmɨ ˈmajʃ kõˈfuzu' WHERE portuguese_text = 'Isto deixou-me mais confuso.';
UPDATE phrases SET ipa_transcription = 'ˈoʒɨ ʃˈtow kõ ˈpokɐ pɐsjẽˈsjɐ' WHERE portuguese_text = 'Hoje estou com pouca paciência.';
UPDATE phrases SET ipa_transcription = 'ˈsĩtu mɨ ˈũ ˈpoku ĩzɨˈɡuɾu ẽ ʁɨlɐˈsɐ̃w ɐ ˈisu' WHERE portuguese_text = 'Sinto-me um pouco inseguro em relação a isso.';
UPDATE phrases SET ipa_transcription = 'ˈiʃtu dɨˈjʃowmɨ bɐʃˈtɐ̃tɨ sɐtiʃˈfɐjtu' WHERE portuguese_text = 'Isto deixou-me bastante satisfeito.';
UPDATE phrases SET ipa_transcription = 'ˈoʒɨ ˈsĩtu mɨ ˈmajʃ iɨkiɫiˈbɾadu' WHERE portuguese_text = 'Hoje sinto-me mais equilibrado.';
UPDATE phrases SET ipa_transcription = 'ʃˈtow ˈũ ˈpoku ˈtẽsu ˈneʃtɨ muˈmẽtu' WHERE portuguese_text = 'Estou um pouco tenso neste momento.';
UPDATE phrases SET ipa_transcription = 'ˈiʃtu mɨˈʃew bɐʃˈtɐ̃tɨ kuˈmiɡu' WHERE portuguese_text = 'Isto mexeu bastante comigo.';
UPDATE phrases SET ipa_transcription = 'ˈsĩtu mɨ ˈmajʃ tɾɐ̃ˈkil̪u dɨˈpojʃ dɨ fɐˈlaɾ' WHERE portuguese_text = 'Sinto-me mais tranquilo depois de falar.';
UPDATE phrases SET ipa_transcription = 'ˈoʒɨ ʃˈtow ɐ sĩˈtiɾmɨ mɨˈʎɔɾ' WHERE portuguese_text = 'Hoje estou a sentir-me melhor.';
UPDATE phrases SET ipa_transcription = 'ˈiʃtu dɨˈjʃowmɨ imusjunɐɫˈmẽtɨ kɐ̃ˈsadu' WHERE portuguese_text = 'Isto deixou-me emocionalmente cansado.';
UPDATE phrases SET ipa_transcription = 'ˈsĩtu mɨ ˈmajʃ kõfiˈɐ̃tɨ kõ u ˈtẽpu' WHERE portuguese_text = 'Sinto-me mais confiante com o tempo.';
UPDATE phrases SET ipa_transcription = 'ˈoʒɨ nɐ̃w mɨ ˈsĩtu ˈmũjtu bẽ' WHERE portuguese_text = 'Hoje não me sinto muito bem.';
UPDATE phrases SET ipa_transcription = 'ˈaʃu kɨ ˈisu dɨˈpẽdɨ dɐ sitwɐˈsɐ̃w' WHERE portuguese_text = 'Acho que isso depende da situação.';
UPDATE phrases SET ipa_transcription = 'tɐɫˈveʃ ˈseʒɐ mɨˈʎɔɾ ʃpɨˈɾaɾ ˈũ ˈpoku' WHERE portuguese_text = 'Talvez seja melhor esperar um pouco.';
UPDATE phrases SET ipa_transcription = 'ẽˈtɐ̃w u kɨ fɐˈzẽmuʃ ɐˈɡɔɾɐ' WHERE portuguese_text = 'Então, o que fazemos agora?';
UPDATE phrases SET ipa_transcription = 'nɐ vɨɾˈdadɨ nɐ̃w pẽˈsaj ˈnisu' WHERE portuguese_text = 'Na verdade, não pensei nisso.';
UPDATE phrases SET ipa_transcription = 'nu ˈfũdu ɛ ˈsẽpɾɨ ɐ ˈmezmɐ ˈkojzɐ' WHERE portuguese_text = 'No fundo, é sempre a mesma coisa.';
UPDATE phrases SET ipa_transcription = 'dɨ kwɐɫˈkɛɾ ˈfɔɾmɐ ˈtẽmuʃ dɨ dɨsɨˈdiɾ' WHERE portuguese_text = 'De qualquer forma, temos de decidir.';
UPDATE phrases SET ipa_transcription = 'ˈpelu ˈmenus tẽˈtamuʃ ʁɨzoɫˈveɾ ˈisu' WHERE portuguese_text = 'Pelo menos tentámos resolver isso.';
UPDATE phrases SET ipa_transcription = 'nu ẽˈtɐ̃tu nɐ̃w ɛ tɐ̃w ˈsĩplɨʃ ɐˈsĩ' WHERE portuguese_text = 'No entanto, não é tão simples assim.';
UPDATE phrases SET ipa_transcription = 'puɾ ˈisu pɾɨˈfiɾu nɐ̃w ɐʁiʃˈkaɾ' WHERE portuguese_text = 'Por isso, prefiro não arriscar.';
UPDATE phrases SET ipa_transcription = 'ẽ ʒɨˈɾaɫ fũˈsjɔnɐ ˈdesɐ ˈfɔɾmɐ' WHERE portuguese_text = 'Em geral, funciona dessa forma.';
UPDATE phrases SET ipa_transcription = 'dɨ ˈsɛɾtɐ ˈfɔɾmɐ kõˈkɔɾdu kõˈtiɡu' WHERE portuguese_text = 'De certa forma, concordo contigo.';
UPDATE phrases SET ipa_transcription = 'poɾ ˈotɾu ˈlaðu ˈveʒu ɐɫˈɡũʃ ˈʁiʃkuʃ' WHERE portuguese_text = 'Por outro lado, vejo alguns riscos.';
UPDATE phrases SET ipa_transcription = 'ɐˈĩdɐ ɐˈsĩ ˈvalɨ ɐ ˈpenɐ tẽˈtaɾ' WHERE portuguese_text = 'Ainda assim, vale a pena tentar.';
UPDATE phrases SET ipa_transcription = 'ˈɐ̃tɨʃ dɨ ˈmajʃ pɾɨziˈzɐmuʃ dɨ ʃklɐɾɨʃˈseɾ ˈiʃtu' WHERE portuguese_text = 'Antes de mais, precisamos de esclarecer isto.';
UPDATE phrases SET ipa_transcription = 'dɨˈpojʃ ˈdisu puˈdɛmuʃ ɐvɐ̃ˈsaɾ' WHERE portuguese_text = 'Depois disso, podemos avançar.';
UPDATE phrases SET ipa_transcription = 'dɨ ɐˈkɔɾdu kõ ˈisu faʃ sẽˈtĩdu ʃpɨˈɾaɾ' WHERE portuguese_text = 'De acordo com isso, faz sentido esperar.';
UPDATE phrases SET ipa_transcription = 'ẽ pɾĩˈsipju nɐ̃w ˈveʒu pɾuˈblɛmɐ' WHERE portuguese_text = 'Em princípio, não vejo problema.';
UPDATE phrases SET ipa_transcription = 'nɐ ˈpɾatikɐ ɐʃ ˈkojzɐʃ sɐ̃w difɨˈɾẽtɨʃ' WHERE portuguese_text = 'Na prática, as coisas são diferentes.';
UPDATE phrases SET ipa_transcription = 'nu fiˈnaɫ ˈtudu dɨˈpẽdɨ du kõˈtɛʃtu' WHERE portuguese_text = 'No final, tudo depende do contexto.';
UPDATE phrases SET ipa_transcription = 'dɨ muˈmẽtu nɐ̃w ˈtẽmuʃ ˈumɐ ʁɨʃˈpɔʃtɐ' WHERE portuguese_text = 'De momento, não temos uma resposta.';
UPDATE phrases SET ipa_transcription = 'ẽ pɾiˈmɐjɾu luˈɡaɾ ˈtẽmuʃ dɨ fɐˈlaɾ ˈdisu' WHERE portuguese_text = 'Em primeiro lugar, temos de falar disso.';
UPDATE phrases SET ipa_transcription = 'ɐˈlẽ ˈdisu a ˈotɾuʃ fɐˈtoɾɨʃ ɐ kõsɨdɨˈɾaɾ' WHERE portuguese_text = 'Além disso, há outros fatores a considerar.';
UPDATE phrases SET ipa_transcription = 'poɾ ẽˈkwɐ̃tu ˈvɐmuʃ dɨjˈʃaɾ ɐˈsĩ' WHERE portuguese_text = 'Por enquanto, vamos deixar assim.';
UPDATE phrases SET ipa_transcription = 'nu ˈminimu pɾɨziˈzɐmuʃ dɨ tẽˈtaɾ' WHERE portuguese_text = 'No mínimo, precisamos de tentar.';
UPDATE phrases SET ipa_transcription = 'ẽ ˈtodu u ˈkazu ˈtẽmuʃ dɨ ɐvɐ̃ˈsaɾ' WHERE portuguese_text = 'Em todo o caso, temos de avançar.';
UPDATE phrases SET ipa_transcription = 'poɾ ɐˈɡɔɾɐ ˈisu ˈʃɛɡɐ' WHERE portuguese_text = 'Por agora, isso chega.';
UPDATE phrases SET ipa_transcription = 'kõ ˈisu ẽ ˈmẽtɨ faʃ sẽˈtĩdu kõtĩˈnwaɾ' WHERE portuguese_text = 'Com isso em mente, faz sentido continuar.';
UPDATE phrases SET ipa_transcription = 'dɨ ˈsɛɾtɐ mɐnɐjˈɾɐ ˈiʃtu ɛ puziˈtivu' WHERE portuguese_text = 'De certa maneira, isto é positivo.';
UPDATE phrases SET ipa_transcription = 'ɐpɨˈzaɾ ˈdisu kõtĩˈnũu kõ ˈduβidɐʃ' WHERE portuguese_text = 'Apesar disso, continuo com dúvidas.';
UPDATE phrases SET ipa_transcription = 'nu ʒɨˈɾaɫ ʃˈtow dɨ ɐˈkɔɾdu' WHERE portuguese_text = 'No geral, estou de acordo.';
UPDATE phrases SET ipa_transcription = 'poɾ ˈesɨ muˈtivu pɾɨziˈzɐmuʃ dɨ ʁɨˈveɾ ˈiʃtu' WHERE portuguese_text = 'Por esse motivo, precisamos de rever isto.';
UPDATE phrases SET ipa_transcription = 'ɐ pɐɾˈtiɾ dɐˈki ˈtudu ˈfikɐ ˈmajʃ ˈklaɾu' WHERE portuguese_text = 'A partir daqui, tudo fica mais claro.';
UPDATE phrases SET ipa_transcription = 'ẽ ʁɨˈzumu ˈtẽmuʃ ˈduɐʃ ɔpˈsɐ̃jʃ' WHERE portuguese_text = 'Em resumo, temos duas opções.';
UPDATE phrases SET ipa_transcription = 'dɨ ˈʁɛʃtu nɐ̃w a ˈmũjtu ɐ ɐkɾɨsẽˈtaɾ' WHERE portuguese_text = 'De resto, não há muito a acrescentar.';
UPDATE phrases SET ipa_transcription = 'kõ u ˈtẽpu ˈisu vaj ʃklɐɾɨʃˈseɾsɨ' WHERE portuguese_text = 'Com o tempo, isso vai esclarecer-se.';
UPDATE phrases SET ipa_transcription = 'ẽtɾɐ̃ˈtɐ̃tu ˈvɐmuʃ ɐvɐ̃ˈsɐ̃du' WHERE portuguese_text = 'Entretanto, vamos avançando.';
UPDATE phrases SET ipa_transcription = 'nu ˈfĩ dɐʃ ˈkõtɐʃ ˈtudu sɨ ʁɨˈzɔɫvɨ' WHERE portuguese_text = 'No fim das contas, tudo se resolve.';
UPDATE phrases SET ipa_transcription = 'dɨ ˈũ ˈmodu ʒɨˈɾaɫ kõˈkɔɾdu kõ ˈisu' WHERE portuguese_text = 'De um modo geral, concordo com isso.';
UPDATE phrases SET ipa_transcription = 'ˈditu ˈiʃtu pɾɨziˈzɐmuʃ dɨ ɐˈʒiɾ' WHERE portuguese_text = 'Dito isto, precisamos de agir.';
UPDATE phrases SET ipa_transcription = 'ɐ pɐɾˈtiɾ dɐˈi ˈtudu muˈdow' WHERE portuguese_text = 'A partir daí, tudo mudou.';
UPDATE phrases SET ipa_transcription = 'ˈiʃtu ɛ ˈumɐ ˈɡɾɐ̃dɨ ˈmɛɾdɐ' WHERE portuguese_text = 'Isto é uma grande merda.';
UPDATE phrases SET ipa_transcription = 'ʃˈtow ˈfaɾtu ˈdeʃtɐ puɾkɐˈɾiɐ ˈtodɐ' WHERE portuguese_text = 'Estou farto desta porcaria toda.';
UPDATE phrases SET ipa_transcription = 'ˈiʃtu kuˈʁew ˈmezmu ˈmaɫ fuˈdɐsɨ' WHERE portuguese_text = 'Isto correu mesmo mal, foda-se.';
UPDATE phrases SET ipa_transcription = 'nɐ̃w pɨɾˈsɛbu ˈeʃtɐ ˈmɛɾdɐ nẽˈũmɐ' WHERE portuguese_text = 'Não percebo esta merda nenhuma.';
UPDATE phrases SET ipa_transcription = 'ˈeʃtɐ sitwɐˈsɐ̃w ʃˈta ɐ daɾmɨ ˈkabu duʃ ˈnɛɾvuʃ' WHERE portuguese_text = 'Esta situação está a dar-me cabo dos nervos.';
UPDATE phrases SET ipa_transcription = 'ˈiʃtu ɛ ˈumɐ pɐʎɐˈsadɐ du kɐˈʁaʎu' WHERE portuguese_text = 'Isto é uma palhaçada do caralho.';
UPDATE phrases SET ipa_transcription = 'ʃˈtow kõplɨtɐˈmẽtɨ liˈʃadu ˈoʒɨ' WHERE portuguese_text = 'Estou completamente lixado hoje.';
UPDATE phrases SET ipa_transcription = 'kɨ sɨ ˈfɔdɐ ʒa nɐ̃w ˈkɛɾu sɐˈbeɾ' WHERE portuguese_text = 'Que se foda, já não quero saber.';
UPDATE phrases SET ipa_transcription = 'ˈiʃtu ɛ ˈmezmu ˈpaɾɐ ɨʃkɨˈseɾ fuˈdɐsɨ' WHERE portuguese_text = 'Isto é mesmo para esquecer, foda-se.';
UPDATE phrases SET ipa_transcription = 'nɐ̃w ˈtẽɲu pɐsjẽˈsjɐ ˈpaɾɐ ˈeʃtɐ ˈmɛɾdɐ' WHERE portuguese_text = 'Não tenho paciência para esta merda.';
UPDATE phrases SET ipa_transcription = 'ʃˈtow kɐ̃ˈsadu ˈdeʃtɐ ˈmɛɾdɐ ˈtodɐ' WHERE portuguese_text = 'Estou cansado desta merda toda.';
UPDATE phrases SET ipa_transcription = 'ˈiʃtu ʃˈta ɐ kuˈʁeɾ ˈkomu u kɐˈʁaʎu' WHERE portuguese_text = 'Isto está a correr como o caralho.';
UPDATE phrases SET ipa_transcription = 'kɨ ˈmɛɾdɐ dɨ ˈdiɐ ɐ ˈsɛɾju' WHERE portuguese_text = 'Que merda de dia, a sério.';
UPDATE phrases SET ipa_transcription = 'nɐ̃w ɐkɾɨˈditu ˈneʃtɐ ˈmɛɾdɐ' WHERE portuguese_text = 'Não acredito nesta merda.';
UPDATE phrases SET ipa_transcription = 'ˈiʃtu nɐ̃w faʃ sẽˈtĩdu nẽˈũ fuˈdɐsɨ' WHERE portuguese_text = 'Isto não faz sentido nenhum, foda-se.';
UPDATE phrases SET ipa_transcription = 'ʃˈtow ɐ pɨɾˈdeɾ ɐ pɐsjẽˈsjɐ kõ ˈiʃtu' WHERE portuguese_text = 'Estou a perder a paciência com isto.';
UPDATE phrases SET ipa_transcription = 'ˈeʃtɐ sitwɐˈsɐ̃w ɛ ˈumɐ ˈmɛɾdɐ pɨˈɡadɐ' WHERE portuguese_text = 'Esta situação é uma merda pegada.';
UPDATE phrases SET ipa_transcription = 'nɐ̃w ˈɛɾɐ suˈpoʃtu seɾ ˈeʃtɐ ˈmɛɾdɐ' WHERE portuguese_text = 'Não era suposto ser esta merda.';
UPDATE phrases SET ipa_transcription = 'ˈiʃtu ʃˈta ɐ iɾ ˈtudu ˈpelu ˈkɐnu ɐˈbajʃu' WHERE portuguese_text = 'Isto está a ir tudo pelo cano abaixo.';
UPDATE phrases SET ipa_transcription = 'ʃˈtow ˈmezmu ˈfaɾtu ˈdeʃtɐ sitwɐˈsɐ̃w' WHERE portuguese_text = 'Estou mesmo farto desta situação.';
UPDATE phrases SET ipa_transcription = 'kɨ ˈputɐ dɨ kõfuzɐ̃w fuˈdɐsɨ' WHERE portuguese_text = 'Que puta de confusão, foda-se.';
UPDATE phrases SET ipa_transcription = 'ˈiʃtu ʃˈta ˈumɐ vɨɾdɐˈdejɾɐ ˈmɛɾdɐ' WHERE portuguese_text = 'Isto está uma verdadeira merda.';
UPDATE phrases SET ipa_transcription = 'nɐ̃w ˈsaj kɨ kɐˈʁaʎu fɐˈzeɾ ɐˈɡɔɾɐ' WHERE portuguese_text = 'Não sei que caralho fazer agora.';
UPDATE phrases SET ipa_transcription = 'ʃˈtow sẽ pɐsjẽˈsjɐ ˈpaɾɐ ˈiʃtu ˈoʒɨ' WHERE portuguese_text = 'Estou sem paciência para isto hoje.';
UPDATE phrases SET ipa_transcription = 'ˈiʃtu dew kõplɨtɐˈmẽtɨ ˈpaɾɐ u ˈtoɾtu' WHERE portuguese_text = 'Isto deu completamente para o torto.';
UPDATE phrases SET ipa_transcription = 'kɨ sɨ ˈliʃɨ ˈtudu pɾɨˈsizu dɨ ˈũ ˈtẽpu' WHERE portuguese_text = 'Que se lixe tudo, preciso de um tempo.';
UPDATE phrases SET ipa_transcription = 'ˈeʃtɐ ˈmɛɾdɐ ʃˈta ɐ ʁɨpɨˈtiɾsɨ ˈsẽpɾɨ' WHERE portuguese_text = 'Esta merda está a repetir-se sempre.';
UPDATE phrases SET ipa_transcription = 'ʃˈtow ˈmezmu a ˈbɐjɾɐ dɨ ɨʃpluˈdiɾ' WHERE portuguese_text = 'Estou mesmo à beira de explodir.';
UPDATE phrases SET ipa_transcription = 'ˈiʃtu ɛ ʃtɾɨˈsɐ̃tɨ ˈpaɾɐ kɐˈʁaʎu' WHERE portuguese_text = 'Isto é stressante para caralho.';
UPDATE phrases SET ipa_transcription = 'ʒa ˈʃɛɡɐ ˈdeʃtɐ ˈmɛɾdɐ' WHERE portuguese_text = 'Já chega desta merda.';
UPDATE phrases SET ipa_transcription = 'nɐ̃w ˈtẽɲu inɨɾˈʒiɐ ˈpaɾɐ liˈdaɾ kõ ˈiʃtu' WHERE portuguese_text = 'Não tenho energia para lidar com isto.';
UPDATE phrases SET ipa_transcription = 'ˈiʃtu ʃˈta ɐ sɐˈiɾ kõplɨtɐˈmẽtɨ du kõˈtɾɔlu' WHERE portuguese_text = 'Isto está a sair completamente do controlo.';
UPDATE phrases SET ipa_transcription = 'ʃˈtow kɐ̃ˈsadu dɨ lɨˈvaɾ kõ ˈeʃtɐ ˈmɛɾdɐ' WHERE portuguese_text = 'Estou cansado de levar com esta merda.';
UPDATE phrases SET ipa_transcription = 'kɨ ˈmɛɾdɐ foj ˈeʃtɐ ɐˈɡɔɾɐ' WHERE portuguese_text = 'Que merda foi esta agora?';
UPDATE phrases SET ipa_transcription = 'ˈiʃtu nɐ̃w ˈpɔdɨ seɾ ˈsɛɾju fuˈdɐsɨ' WHERE portuguese_text = 'Isto não pode ser sério, foda-se.';
UPDATE phrases SET ipa_transcription = 'ʃˈtow ˈmezmu sɐtuˈɾadu ˈdeʃtɐ puɾkɐˈɾiɐ' WHERE portuguese_text = 'Estou mesmo saturado desta porcaria.';
UPDATE phrases SET ipa_transcription = 'ˈtudu ˈiʃtu ɛ ˈumɐ ˈpɛɾdɐ dɨ ˈtẽpu du kɐˈʁaʎu' WHERE portuguese_text = 'Tudo isto é uma perda de tempo do caralho.';
UPDATE phrases SET ipa_transcription = 'ˈiʃtu ʃˈta ɐ daɾ ˈkabu dɨ mĩ' WHERE portuguese_text = 'Isto está a dar cabo de mim.';
UPDATE phrases SET ipa_transcription = 'nɐ̃w ˈtẽɲu kɐˈbesɐ ˈpaɾɐ ˈeʃtɐ ˈmɛɾdɐ ˈoʒɨ' WHERE portuguese_text = 'Não tenho cabeça para esta merda hoje.';
UPDATE phrases SET ipa_transcription = 'vo fɐˈzeɾʎɨ ˈumɐ pɾuˈpɔʃtɐ iʁɨkuzɐˈvɛɫ' WHERE portuguese_text = 'Vou fazer-lhe uma proposta irrecusável.';
UPDATE phrases SET ipa_transcription = 'ɐˈki ʃˈta u ˈʒɔni' WHERE portuguese_text = 'Aqui está o Johnny.';
UPDATE phrases SET ipa_transcription = 'ɐ ˈvidɐ ɛ ˈkomu ˈumɐ ˈkajʃɐ dɨ ʃokuˈlatɨʃ' WHERE portuguese_text = 'A vida é como uma caixa de chocolates.';
UPDATE phrases SET ipa_transcription = 'nĩˈɡẽj pɐ̃w u ˈbeɪbi nũ ˈkɐ̃tu' WHERE portuguese_text = 'Ninguém põe o Baby num canto.';
UPDATE phrases SET ipa_transcription = 'vo βuɫˈtaɾ' WHERE portuguese_text = 'Vou voltar.';
UPDATE phrases SET ipa_transcription = 'ˈhustõ ˈtẽmuʃ ˈũ pɾuˈblɛmɐ' WHERE portuguese_text = 'Houston, temos um problema.';
UPDATE phrases SET ipa_transcription = 'ɐˈtɛ ɐˈki ˈtudu bẽ' WHERE portuguese_text = 'Até aqui, tudo bem.';
UPDATE phrases SET ipa_transcription = 'so dɨmɐzjɐˈdu ˈvɛʎu ˈpaɾɐ ˈiʃtu' WHERE portuguese_text = 'Sou demasiado velho para isto.';
UPDATE phrases SET ipa_transcription = 'kɨ ɐ ˈfɔɾsɐ ɨʃˈtɛʒɐ kõˈtiɡu' WHERE portuguese_text = 'Que a força esteja contigo.';
UPDATE phrases SET ipa_transcription = 'nɐ̃w ʃˈtɐmuʃ ˈmajʃ nu ˈkɐ̃zɐʃ' WHERE portuguese_text = 'Não estamos mais no Kansas.';
UPDATE phrases SET ipa_transcription = 'ˈveʒu pɨˈsoɐʃ ˈmɔɾtɐʃ' WHERE portuguese_text = 'Vejo pessoas mortas.';
UPDATE phrases SET ipa_transcription = 'ˈmɔʃtɾɐmɨ u dĩˈɲejɾu' WHERE portuguese_text = 'Mostra-me o dinheiro!';
UPDATE phrases SET ipa_transcription = 'ˈiʃtu ɛ u iˈnisju dɨ ˈaɫɡu ˈɡɾɐ̃dɨ' WHERE portuguese_text = 'Isto é o início de algo grande.';
UPDATE phrases SET ipa_transcription = 'ew so u ˈʁɐj du ˈmũdu' WHERE portuguese_text = 'Eu sou o rei do mundo!';
UPDATE phrases SET ipa_transcription = 'kõtĩˈnũɐmuʃ ɐ kuˈʁeɾ' WHERE portuguese_text = 'Continuamos a correr.';
UPDATE phrases SET ipa_transcription = 'puɾˈkɛ tɐ̃w ˈsɛɾju' WHERE portuguese_text = 'Porque tão sério?';
UPDATE phrases SET ipa_transcription = 'vo fɐˈzeɾ ˈiʃtu a ˈmiɲɐ mɐnɐjˈɾɐ' WHERE portuguese_text = 'Vou fazer isto à minha maneira.';
UPDATE phrases SET ipa_transcription = 'ʒa nɐ̃w a ˈβɔɫtɐ ɐ ˈdaɾ' WHERE portuguese_text = 'Já não há volta a dar.';
UPDATE phrases SET ipa_transcription = 'ˈeɫɨʃ ˈpɔdẽj ˈtiɾɐɾnuʃ ɐ ˈvidɐ mɐʃ nɐ̃w ɐ libɨɾˈdadɨ' WHERE portuguese_text = 'Eles podem tirar-nos a vida, mas não a liberdade.';
UPDATE phrases SET ipa_transcription = 'ew ˈveʒu tɨ' WHERE portuguese_text = 'Eu vejo-te.';
UPDATE phrases SET ipa_transcription = 'ˈvɐmuʃ ʁɨzoɫˈveɾ ˈiʃtu' WHERE portuguese_text = 'Vamos resolver isto.';
UPDATE phrases SET ipa_transcription = 'ɛ ˈisu kɨ fɐˈzẽmuʃ' WHERE portuguese_text = 'É isso que fazemos.';
UPDATE phrases SET ipa_transcription = 'ɐˈĩdɐ a ɨʃpɨˈɾɐ̃sɐ' WHERE portuguese_text = 'Ainda há esperança.';
UPDATE phrases SET ipa_transcription = 'ˈtẽmuʃ dɨ fɐˈlaɾ' WHERE portuguese_text = 'Temos de falar.';
UPDATE phrases SET ipa_transcription = 'ˈtudu vaj fiˈkaɾ bẽ' WHERE portuguese_text = 'Tudo vai ficar bem.';

-- Cluster 3 transcriptions (added separately)
UPDATE phrases SET ipa_transcription = 'nɐ̃w pɨɾsɨˈbi bẽ u kɨ kiʃ dɨˈzeɾ' WHERE portuguese_text = 'Não percebi bem o que quis dizer.';
UPDATE phrases SET ipa_transcription = 'ɐˈɡɔɾɐ pɨɾˈsɛbu mɨˈʎɔɾ ɐ sitwɐˈsɐ̃w' WHERE portuguese_text = 'Agora percebo melhor a situação.';
UPDATE phrases SET ipa_transcription = 'ˈpɔdɨ ʃplɨˈkaɾ ˈisu dɨ ˈotɾɐ ˈfɔɾmɐ' WHERE portuguese_text = 'Pode explicar isso de outra forma?';
UPDATE phrases SET ipa_transcription = 'ɐˈĩdɐ nɐ̃w ʃˈta totɐɫˈmẽtɨ ˈklaɾu ˈpaɾɐ mĩ' WHERE portuguese_text = 'Ainda não está totalmente claro para mim.';
UPDATE phrases SET ipa_transcription = 'ˈaʃu kɨ ẽtẽˈdi ɐ iˈdɐjɐ ʒɨˈɾaɫ' WHERE portuguese_text = 'Acho que entendi a ideia geral.';
UPDATE phrases SET ipa_transcription = 'nɐ̃w ˈtẽɲu ɐ sɨɾˈtezɐ sɨ kõpɾɨẽˈdi bẽ' WHERE portuguese_text = 'Não tenho a certeza se compreendi bem.';
UPDATE phrases SET ipa_transcription = 'ˈisu ɐˈʒudɐmɨ ɐ pɨɾsɨˈbeɾ mɨˈʎɔɾ' WHERE portuguese_text = 'Isso ajuda-me a perceber melhor.';
UPDATE phrases SET ipa_transcription = 'kõtiˈnũu kõ aɫˈɡũmɐʃ ˈduβidɐʃ ˈsobɾɨ ˈisu' WHERE portuguese_text = 'Continuo com algumas dúvidas sobre isso.';
UPDATE phrases SET ipa_transcription = 'ˈpɔdɨ daɾmɨ ˈũ ẽˈzẽplu ˈmajʃ kõˈkɾetu' WHERE portuguese_text = 'Pode dar-me um exemplo mais concreto?';
UPDATE phrases SET ipa_transcription = 'ɐˈɡɔɾɐ faʃ ˈmũjtu ˈmajʃ sẽˈtĩdu ˈpaɾɐ mĩ' WHERE portuguese_text = 'Agora faz muito mais sentido para mim.';
UPDATE phrases SET ipa_transcription = 'nɐ̃w ʃˈtow ɐ pɨɾsɨˈbeɾ bẽ ˈeʃtɐ ˈpaɾtɨ' WHERE portuguese_text = 'Não estou a perceber bem esta parte.';
UPDATE phrases SET ipa_transcription = 'ˈpɔdɨ ʁɨpɨˈtiɾ ˈesɐ ˈpaɾtɨ ˈotɾɐ ˈveʃ' WHERE portuguese_text = 'Pode repetir essa parte outra vez?';
UPDATE phrases SET ipa_transcription = 'pɨɾˈsɛbu u kɨ kɛɾ dɨˈzeɾ ẽ ˈpaɾtɨ' WHERE portuguese_text = 'Percebo o que quer dizer, em parte.';
UPDATE phrases SET ipa_transcription = 'nɐ̃w kõsɨˈɡi ɐkõpɐˈɲaɾ ˈtudu u kɨ ˈdisɨ' WHERE portuguese_text = 'Não consegui acompanhar tudo o que disse.';
UPDATE phrases SET ipa_transcription = 'ˈpɔdɨ fɐˈlaɾ ˈũ ˈpoku ˈmajʃ dɨvɐˈɡaɾ' WHERE portuguese_text = 'Pode falar um pouco mais devagar?';
UPDATE phrases SET ipa_transcription = 'ˈisu nɐ̃w fiˈko ˈmũjtu ˈklaɾu ˈpaɾɐ mĩ' WHERE portuguese_text = 'Isso não ficou muito claro para mim.';
UPDATE phrases SET ipa_transcription = 'ɐˈɡɔɾɐ pɨɾˈsɛbu u kɨ ɨʃˈtaβɐ ɐ dɨˈzeɾ' WHERE portuguese_text = 'Agora percebo o que estava a dizer.';
UPDATE phrases SET ipa_transcription = 'ɐˈĩdɐ ˈtẽɲu difiˈkuɫdadɨ ẽ pɨɾsɨˈbeɾ ˈisu' WHERE portuguese_text = 'Ainda tenho dificuldade em perceber isso.';
UPDATE phrases SET ipa_transcription = 'ˈpɔdɨ ʃplɨˈkaɾ ˈisu ˈpasu ɐ ˈpasu' WHERE portuguese_text = 'Pode explicar isso passo a passo?';
UPDATE phrases SET ipa_transcription = 'ˈisu kuˈmɛsɐ ɐ fɐˈzeɾ sẽˈtĩdu ɐˈɡɔɾɐ' WHERE portuguese_text = 'Isso começa a fazer sentido agora.';
UPDATE phrases SET ipa_transcription = 'nɐ̃w ˈtẽɲu ɐ sɨɾˈtezɐ sɨ ẽtẽˈdi kuʁɨtɐˈmẽtɨ' WHERE portuguese_text = 'Não tenho a certeza se entendi corretamente.';
UPDATE phrases SET ipa_transcription = 'ˈpɔdɨ klɐɾifiˈkaɾ ˈũ ˈpoku mɨˈʎɔɾ' WHERE portuguese_text = 'Pode clarificar um pouco melhor?';
UPDATE phrases SET ipa_transcription = 'ˈpeɾdimɨ ˈũ ˈpoku ɐ ˈmeju dɐ ʃplɨkɐˈsɐ̃w' WHERE portuguese_text = 'Perdi-me um pouco a meio da explicação.';
UPDATE phrases SET ipa_transcription = 'ˈisu nɐ̃w koʁɨʃˈpõdɨ aw kɨ ew ẽtẽˈdi' WHERE portuguese_text = 'Isso não corresponde ao que eu entendi.';
UPDATE phrases SET ipa_transcription = 'ɐˈɡɔɾɐ ʃˈta ˈmajʃ ˈklaɾu ˈpaɾɐ mĩ' WHERE portuguese_text = 'Agora está mais claro para mim.';
UPDATE phrases SET ipa_transcription = 'ˈpɔdɨ dɨˈzeɾ ˈisu dɨ mɐnɐjˈɾɐ ˈmajʃ ˈsĩplɨʃ' WHERE portuguese_text = 'Pode dizer isso de maneira mais simples?';
UPDATE phrases SET ipa_transcription = 'nɐ̃w ɐkõpɐˈɲaj bẽ ˈesɐ ˈpaɾtɨ' WHERE portuguese_text = 'Não acompanhei bem essa parte.';
UPDATE phrases SET ipa_transcription = 'ˈaʃu kɨ ɐˈɡɔɾɐ ʃˈtow ɐ pɨɾsɨˈbeɾ' WHERE portuguese_text = 'Acho que agora estou a perceber.';
UPDATE phrases SET ipa_transcription = 'ˈisu ʃklɐɾɨˈsɛsɨ bɐʃˈtɐ̃tɨ ɐʃ ˈkojzɐʃ' WHERE portuguese_text = 'Isso esclarece bastante as coisas.';
UPDATE phrases SET ipa_transcription = 'ˈpɔdɨ kõfiɾˈmaɾ sɨ ẽtẽˈdi bẽ' WHERE portuguese_text = 'Pode confirmar se entendi bem?';
UPDATE phrases SET ipa_transcription = 'ɐˈĩdɐ pɾɨˈsizu dɨ ɐɫˈɡũ ˈtẽpu ˈpaɾɐ ẽtẽˈdeɾ' WHERE portuguese_text = 'Ainda preciso de algum tempo para entender.';
UPDATE phrases SET ipa_transcription = 'nɐ̃w ʃˈtow ɐ kõsɨˈɡiɾ pɨɾsɨˈbeɾ ˈiʃtu ɐˈɡɔɾɐ' WHERE portuguese_text = 'Não estou a conseguir perceber isto agora.';
UPDATE phrases SET ipa_transcription = 'ˈisu foj ʃplɨˈkadu dɨ ˈfɔɾmɐ ˈklaɾɐ' WHERE portuguese_text = 'Isso foi explicado de forma clara.';
UPDATE phrases SET ipa_transcription = 'ɐˈɡɔɾɐ kõˈsiɡu ˈveɾ ɐ ˈlɔʒikɐ ˈdisu' WHERE portuguese_text = 'Agora consigo ver a lógica disso.';
UPDATE phrases SET ipa_transcription = 'ɐˈĩdɐ ˈtẽɲu aɫˈɡũmɐʃ pɾɨˈɡũtɐʃ ˈsobɾɨ ˈisu' WHERE portuguese_text = 'Ainda tenho algumas perguntas sobre isso.';
UPDATE phrases SET ipa_transcription = 'ˈpɔdɨ βuɫˈtaɾ ɐ ʃplɨˈkaɾ ɐ ˈuɫtimɐ ˈpaɾtɨ' WHERE portuguese_text = 'Pode voltar a explicar a última parte?';
UPDATE phrases SET ipa_transcription = 'ˈisu ɐˈʒudɐmɨ ɐ ẽtẽˈdeɾ mɨˈʎɔɾ u kõˈtɛʃtu' WHERE portuguese_text = 'Isso ajuda-me a entender melhor o contexto.';
UPDATE phrases SET ipa_transcription = 'ˈaʃu kɨ ɐˈɡɔɾɐ ẽtẽˈdi kuʁɨtɐˈmẽtɨ' WHERE portuguese_text = 'Acho que agora entendi corretamente.';
UPDATE phrases SET ipa_transcription = 'ɐˈĩdɐ nɐ̃w kõsɨˈɡi pɨɾsɨˈbeɾ ˈtudu' WHERE portuguese_text = 'Ainda não consegui perceber tudo.';
UPDATE phrases SET ipa_transcription = 'uβɾiˈɡadu puɾ ʃplɨˈkaɾ kõ ˈtɐ̃tɐ klɐˈɾezɐ' WHERE portuguese_text = 'Obrigado por explicar com tanta clareza.';
